name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0.402'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build local Docker image
        run: ls ${{ github.workspace }} #dotnet publish --arch x64 --os linux ${{ github.workspace }}/BLART.sln
      # - name: Push to Docker Hub
        # run: docker push xroier/blart:latest
